#!/bin/sh -x
for GOOS in darwin linux solaris; do
    # No need to build for 386 these days.
    for GOARCH in amd64 arm; do
        env GOOS=$GOOS GOARCH=$GOARCH go build -o bin/fiod-$GOOS-$GOARCH rmcneal.com/fiod
        env GOOS=$GOOS GOARCH=$GOARCH go build -o bin/auto-fiod-$GOOS-$GOARCH auto-fiod
        env GOOS=$GOOS GOARCH=$GOARCH go build -o bin/hexdmp-$GOOS-$GOARCH rmcneal.com/hexdmp
        env GOOS=$GOOS GOARCH=$GOARCH go build -o bin/uscsi-$GOOS-$GOARCH rmcneal.com/uscsi
    done
done
