#!/bin/sh -x
for GOOS in darwin linux solaris; do
    for GOARCH in 386 amd64; do
        env GOOS=$GOOS GOARCH=$GOARCH go build -v -o bin/fiod-$GOOS-$GOARCH rmcneal.com/fiod
        env GOOS=$GOOS GOARCH=$GOARCH go build -v -o bin/auto-fiod-$GOOS-$GOARCH auto-fiod
    done
done
